[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
  X-Frame-Options = "ALLOW-FROM *"
  X-XSS-Protection = "0"
  Access-Control-Allow-Origin = "*"
