export default () => ({
  alerts: [],
  fullPageLoading: true,
  session: "",
  language: "en",
  region: "es",
  environment: "",
  nonce: "",
  commitId: "",
  branchId: "",
  hashKey: "",
  ip: "",
  crewStatus: "",
  userEmail: "",
  userFirstName: "",
  userLastName: "",
  userId: "",
  crewUniqueId: "",
  crewVerification: ""
});
